### ISSUE TITLE
Builtin stat() function lacks hover support

### ISSUE THREAD

**Issue by ajkrupka** [japhib/pico8-ls#1]
When viewing the pico8 function `stat()`, the Language Server reports "undefined function".

![image](https://user-images.githubusercontent.com/47955634/154077031-30aca0cd-142d-41ee-8ec0-6ad4020a235e.png)

**Comment by japhib** [comment]
Thanks for reporting - this should be an easy fix.

**Comment by japhib** [comment]
Fixed with 0.3.1
