### ISSUE TITLE
Support one-line `while` statement

### ISSUE THREAD

**Issue by japhib** [japhib/pico8-ls#11]
This is used in the `jelpi.p8` demo cart. The line looks like this:

```
while (ta < a-.5) ta += 1
```

I think it's very similar to the single-line `if` statement.

**Comment by miguno** [comment]
I run across the same issue. PICO-8 extends standard Lua syntax with a few shorthands, including for single-line `while` and `if` statements: https://www.lexaloffle.com/dl/docs/pico-8_manual.html#PICO_8_Shorthand

**Comment by japhib** [comment]
Everything else you mentioned is already supported, just the one line while loop is not

**Comment by miguno** [comment]
Yep, exactly.

**Comment by rabensm** [comment]
Any chance this could be prioritized? The "'do' expected" warnings are making me sad. (And yes, I'm working around it by adding `do` and `end` to my one-liners.)

I'd take a crack at a PR myself. I know `Parser.parseWhileStatement`‎ needs some special-case logic like [this](https://github.com/japhib/pico8-ls/blob/ddd7929e08416e0b363e92dff198612484284e67/server/src/parser/parser.ts#L572), but all the special edge cases and one-off manual finagling in there scares me a bit. A lot of that mess is dealing with the possible `else` block, though, so I'm guessing the logic for `Parser.parseWhileStatement` would be simpler.

**Comment by japhib** [comment]
Go for it! I haven't had much time to work on this myself but I'm happy to review PRs, and provide any pointers if you get stuck.

**Comment by japhib** [comment]
Fix is merged into master. I'll post another comment the next time this is released (hopefully in the next day or two).

**Comment by miguno** [comment]
Thank you!

**Comment by japhib** [comment]
Released with 0.5.4 just now.
