### ISSUE TITLE
Code collapsing broken

### ISSUE THREAD

**Issue by desmondw** [japhib/pico8-ls#15]
Code blocks like functions collapse prematurely on other, unrelated `end statements. It ignores nested code blocks, both by keyword and indentation.

Open:
![image](https://user-images.githubusercontent.com/1052705/170852228-940e88e6-c7c3-4f79-816a-f45fff54aed2.png)

Closed:
![image](https://user-images.githubusercontent.com/1052705/170852236-b0770b64-21ba-4870-9bb5-0f4db8c72573.png)

**Comment by japhib** [comment]
Fixed with 0.4.1
