### ISSUE TITLE
Auto complete inconsistency and a bug?

### ISSUE THREAD

**Issue by TheRoboZ** [japhib/pico8-ls#25]
I noticed an inconsistent behavior in autocomplete suggestion, might be a VS code thing though,

Here's a video and here's the best description I can give:

https://youtu.be/wKAyuk2R_gs

If I type a variable name, such as "prince" I correctly get a list of all its fields, but as soon as I type the "." and another letter, it switches back to all members containing that letter instead of reducing the fields to those starting with the letter.

This BUG instead happens from time to time after getting the last update:

when just typing and tabbing to autocomplete it will select the member with the addition of the existing var name, so if i type prince.flip then TAB, I will get prince.prince.flip instead. I couldn't reproduce this in the video, so I manually shows you how it looks, but it happened right before I decided to record the video.

**Comment by japhib** [comment]
Fixed and released with 0.5.2 just now
