### ISSUE TITLE
How to make pico8-ls aware of globals?

### ISSUE THREAD

**Issue by beetrootpaul** [japhib/pico8-ls#28]
How can I make pico8-ls aware of globals I have defined in another file and use across my codebase?

Here you can see on the screenshot how files within my `src` are marked orange due to warnings. When I look into some file, it seems like for example `new_static_sprite` and `_color_15_peach` are marked as "undefined variable".

Those variables come from other files. All files of my game are included in the `.p8` file (and order of includes doesn't matter for most of files, since those usages are within functions… or at least I haven't stumble on any error in PICO-8 so far)

<img width="1037" alt="screenshot 2022-10-18 at 10 06 03" src="https://user-images.githubusercontent.com/92947323/196373004-9c90d683-ef54-4d80-8661-8aedf00f02c4.png">

**Comment by beetrootpaul** [comment]
just in case:

- file from the screenshot: https://github.com/beetrootpaul/dart-07/blob/981a706477247c658281e8a64537ad8dab042dd6/src/cart_main/screen_controls.lua#L5-L16
- `new_static_sprite` definition: https://github.com/beetrootpaul/dart-07/blob/d1089fca72437a6fc052f2cddcfd81c0a8756eaa/src/common/sprites/static_sprite.lua#L5-L9
- `_color_15_peach` definition: https://github.com/beetrootpaul/dart-07/blob/d1089fca72437a6fc052f2cddcfd81c0a8756eaa/src/common/colors.lua#L7
- and the entire project: https://github.com/beetrootpaul/dart-07

**Comment by japhib** [comment]
It should be aware of globals as long as they're all `#include`'ed into the same .p8 file. I'll mark this as a bug.

**Comment by beetrootpaul** [comment]
just a random thought: what if having 4 different p8 files (with different sets of includes) messes things up?

**Comment by beetrootpaul** [comment]
ah, I think I have a lead! See, my p8 files do NOT include from `src/` (where my code lives) but from `build/` (where minified code ends in result of a `npm start` script).

If this is the culprit, then probably this is not a bug, just might be good to have a way to disable those warnings in plugin settings? 🤔 (OFC I would love for pico8-ls to take care of my globals, but if this cannot be easily done in my setup, then I prefer to turn off those particular warnings)

**Comment by japhib** [comment]
That would do it!
