### ISSUE TITLE
Support #include files

### ISSUE THREAD

**Issue by japhib** [japhib/pico8-ls#3]
Support go-to-definition and all the other features for files that are #include'ed into a cartridge.

**Comment by thomasdziedzic** [comment]
When using this plugin and having a single include in my .p8 file:

```lua
#include main.lua
```

I get an error from the extension:

```
unexpected symbol '#' near 'include'
```

Is this expected until this feature is implemented?

**Comment by japhib** [comment]
Yeah, although it’d be a pretty quick change to at least not have it emit an error for the #include statement itself

**Comment by japhib** [comment]
Fixed with 0.4.0 (#include files are now fully supported)

**Comment by scambier** [comment]
Hello :)

The syntax itself works, but variables and functions declared in another file are not recognized

Here, I have `board.lua` and `main.lua` included in `game.p8`. When I reference `Board` in `main.lua`, this warning is displayed:
![image](https://user-images.githubusercontent.com/3216752/170566386-292c5c42-11c8-495f-93b4-4dddf492ea02.png)

**Comment by japhib** [comment]
Fixed with 0.4.1
