### ISSUE TITLE
Labels are marked undefined unless defined before goto

### ISSUE THREAD

**Issue by mika76** [japhib/pico8-ls#32]
I see in #16 there was a fix for labels, but it seems to work only if the label is defined before the goto, if for eg you want to jump out of a couple of loops to a label below it is still marked as undefined (but works fine in pico-8)

![Screenshot 2022-11-30 at 08 02 35](https://user-images.githubusercontent.com/229311/204729428-8cea2108-0b98-4f73-9a66-b273bf322a31.png)

**Comment by japhib** [comment]
That makes sense, I think when checking `goto`s it just naively looks for labels defined _before_ it only. This should probably be a quick fix.

**Comment by japhib** [comment]
Fix released just now with 0.4.10
