### ISSUE TITLE
reset() not recognized

### ISSUE THREAD

**Issue by miguno** [japhib/pico8-ls#35]
pico8-ls reports the pico-8 built-in function [reset()](https://www.lexaloffle.com/dl/docs/pico-8_manual.html#RESET) as "undefined variable: reset", see screenshot. The code is pico-8's default `jelpi.p8` cart.

<img width="461" alt="Screenshot 2022-12-15 at 16 30 24" src="https://user-images.githubusercontent.com/294849/207901178-f5d12705-9ad2-429b-9069-43546202ac7c.png">

**Comment by miguno** [comment]
Thanks for the quick reply!  PR is up at https://github.com/japhib/pico8-ls/pull/36

**Comment by japhib** [comment]
Merged!

**Comment by miguno** [comment]
Thank you!

**Comment by japhib** [comment]
Released with 0.4.9 just now -- new version should be available in vscode within a few minutes.
