### ISSUE TITLE
Auto-complete for built-in functions

### ISSUE THREAD

**Issue by japhib** [japhib/pico8-ls#39]
Once you've typed a built-in function, you can hover it and it'll show the docs for it. But when you've only typed part of the name, there's no auto-complete for it.

**Comment by musjj** [comment]
I'm having this problem, I thought that there was something wrong with my LSP setup on neovim.
Was there a regression? The demo video on the readme shows the completion working just fine.

**Comment by japhib** [comment]
Yes, this might be a regression.
