### ISSUE TITLE
autocomplete duplicates table and access operator

### ISSUE THREAD

**Issue by Minimistro32** [japhib/pico8-ls#40]
If I a return a table from a function, when I enter the table name and the 'dot' operator, autocomplete duplicates the table name and dot operator I already typed. (Here I am returning the table from an included file, but after further testing I realized that isn't a requirement to reproduce the bug.)

I'm unfamiliar with language servers and the code base for this extension, but I wonder if the entire `table.property` is being interpreted as one unit because the table definition isn't obvious.

<hr>

**BEFORE**
Main File:
![bug_kate_p8_—_carts](https://user-images.githubusercontent.com/65469567/231232279-6faea8a4-836c-4d5d-b5ed-ab93fad675f2.png)
Included File:
![bug_lua_—_carts](https://user-images.githubusercontent.com/65469567/231232489-07f29ae7-7b7e-4d98-8a47-1b2b17ad3589.png)

**AFTER**
![bug_kate_p8_—_carts](https://user-images.githubusercontent.com/65469567/231233240-2e5751ae-091a-4d55-8067-0683fd86177c.png)

**Comment by japhib** [comment]
Fixed with https://github.com/japhib/pico8-ls/commit/c82df210a67086b252e06fcaea3fd018823b77d3, not released yet but planning on cutting a release soon

**Comment by japhib** [comment]
Released with 0.5.2 just now
