### ISSUE TITLE
code formatting breaks my game

### ISSUE THREAD

**Issue by reydelatorre** [japhib/pico8-ls#42]
the autoformatting feature breaks my game.  removes parenthesis from arithmetic operations which breaks operator precedence.

**Comment by japhib** [comment]
Sorry @reydelatorre, for some reason I missed the notification about this issue until now. Happy to re-open if you can provide an example of what it formats incorrectly. It’s supposed to only add/remove where it won’t impact correctness, so I do want to fix it where it’s breaking things.
