### ISSUE TITLE
Formatter removing necessary parentheses in math

### ISSUE THREAD

**Issue by icegoat9** [japhib/pico8-ls#50]
I saw some unexpected program behavior after autoformatting, and tracked it down to the formatter removing necessary parentheses in math expressions, which changes the order of operations.

Simple example:
```
x = 20 - (2 + 3 * 4)
```

autoformats to:
```
x = 20 - 2 + 3 * 4
```

Another example:
```
x = not (true and false)
```

Autoformats to the logically different expression:
```
x = not true and false
```

**Comment by amccollum** [comment]
I am also running into this issue. The following code will have the parentheses incorrectly removed:

> `x = 8 / (8 \ 8)`

Strangely, the formatter will maintain the parentheses correctly in the below example, even though the `\` and `/` operators should have the same precedence:

> `x = 8 / (8 / 8)`

Hopefully this helps narrow down the issue!

**Comment by japhib** [comment]
Released just now with `0.5.7` - lmk if you continue to see the issue!

**Comment by amccollum** [comment]
Awesome — thanks for the quick fix! I spent a bit of time trying to track it down myself, but when precedence didn't explain it, I wasn't sure where to go next. The latest version seems to address the issue for me, though!

**Comment by japhib** [comment]
Glad to hear it! For what it’s worth, I didn’t end up fixing the precedence either. The fix takes the cop-out route of just leaving parentheses in where the user has put them :)
