### ISSUE TITLE
[Feature Request]: Publish to Open VSX

### ISSUE THREAD

**Issue by PhasecoreX** [japhib/pico8-ls#54]
Hello!

I would like for this extension to be published on [open-vsx.org](https://open-vsx.org/). That way, VSCodium (and other VS Code-like editors that use Open VSX) can see it and keep the plugin up to date.

Thank you!

**Comment by japhib** [comment]
Thank you for the suggestion! I am a bit  swamped for time these days but will take a stab at this the next time I get a chance to work on this project again.

in the meantime, if you’d like to streamline the process for me to publish there, maybe you could help by telling me what steps I need to take to do so? Or simply linking a page with instructions would also be helpful. No worries either way though.

**Comment by PhasecoreX** [comment]
I haven't done it myself, but I think you just go to the [publish extension page](https://open-vsx.org/user-settings/extensions), log in with GitHub, and then go back to the publish extension page and upload the vsix file. There's probably a page after upload to put in details about the plugin, choose a name and a namespace, not sure what else.

There's also the [automated GitHub actions way](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) they recommend doing too.

**Comment by japhib** [comment]
done: https://open-vsx.org/extension/PollywogGames/pico8-ls

I set up CI publishing so it should be automatically updated in the future too.
