### ISSUE TITLE
New conditional syntax IF ... DO ... END is marked as an error

### ISSUE THREAD

**Issue by malmontagne** [japhib/pico8-ls#57]
Since 0.2.6 we can write if statement like this

`if a==2 do b=1 end` in addition to more traditional `if then`

Doing so in VS Code with pico8-ls give some error "statement expected near do"

**Comment by japhib** [comment]
Completed with the referenced commit ^ in master. I'll update once it's been released.

**Comment by japhib** [comment]
Released with 0.5.4 just now.
