### ISSUE TITLE
Autocomplete broken after update 0.5.2

### ISSUE THREAD

**Issue by Rikaisan** [japhib/pico8-ls#62]
If I start typing, I get the autocomplete suggestions as intended (some are missing, but that's not as much as an issue as what I'll describe)
![image](https://github.com/user-attachments/assets/c1652c19-937c-47d0-ac5e-156ca4c2d832)
However, after pressing enter or tab on it, it replaces what I was typing with only what's after the last dot, so in the case of the previous image, pressing enter results in just `down` if `version >= 0.5.2`
![image](https://github.com/user-attachments/assets/25620955-08ff-4c79-8c58-67989e25ad78)

However, on `version <= 0.5.1` it works as intended, placing the full `player.is_colliding.down`
![image](https://github.com/user-attachments/assets/261cc339-35c8-4950-9ad9-8929c993670d)

I'm pretty sure #40 is the issue that broke auto-complete since it's the only related change and everything works perfectly in `<= 0.5.1`

I also made sure only `pico8-ls` is enabled on the current workspace

**Comment by Rikaisan** [comment]
I tried fixing it myself and I investigated a bit...in theory VSCode should automatically handle the autocomplete issue mentioned on #40
The server should not need to do anything other than provide the full completion, however, for some reason, it isn't working the way it was intended and I can't figure out why...

**Comment by japhib** [comment]
Thanks for reporting. I’ll take a look at this when I get a chance.

**Comment by japhib** [comment]
Fixed and released with 0.5.5

**Comment by japhib** [comment]
@Rikaisan lmk if this fixes it for you. I'm now using `textEdit` instead of just `insertText` so it spells it out exactly for VSCode what text should be replaced when you accept the completion.

**Comment by Rikaisan** [comment]
@japhib I don't know how you figured it out, but it works flawlessly!
Thank you very much!

There's still some issues with not all possible autocompletions being displayed, but that's not a big deal compared to how disruptive this was when working with nested tables.

**Comment by japhib** [comment]
Glad to hear it!

just curious if you have any examples of specific auto completion suggestions you’d like to see? The parsing engine is a bit primitive so it doesn’t have any fancy things like type inference - but there are probably other low hanging fruit that could be considered.
