### ISSUE TITLE
Support built in globals

### ISSUE THREAD

**Issue by Lexicality** [japhib/pico8-ls#9]
All the uppercase symbols (eg 🅾️) are constants, but the language server says they're undefined.
Examples from `demos/api.p8`:
```lua
	if (btn(❎)) then
	 camera(cos(t()/6)*20,0)
	 clip(4,16,120,96)--x,y,w,h
	end
```
```lua
	fillp(░)
	circfill(64,160,52,7)
	fillp() -- reset
```

**Comment by japhib** [comment]
Fixed with 0.4.0

**Comment by joeygibson** [comment]
How do you actually enter these characters? Typing Shift-L in Pico-8 gives the ⬅️ glyph, but in VSCode, it just give me an "L". I've been entering these glyphs in Pico-8, and then switching back to VSCode, but if there's a way to actually type them in VSCode, I'd love to know it.

**Comment by Lexicality** [comment]
> How do you actually enter these characters? Typing Shift-L in Pico-8 gives the ⬅️ glyph, but in VSCode, it just give me an "L". I've been entering these glyphs in Pico-8, and then switching back to VSCode, but if there's a way to actually type them in VSCode, I'd love to know it.

When I opened the issue I was trying to edit a pre-existing script, but you should be able to add all the symbols from your OS's emoji picker, eg

- <kbd>win</kbd>+<kbd>;</kbd>
- <kbd>cmd</kbd>+<kbd>ctrl</kbd>+<kbd>space</kbd>
- <kbd>ctrl</kbd>+<kbd>+</kbd>

**Comment by joeygibson** [comment]
Oh, for Pete's sake... I didn't even think about entering them that way. 🤦🏻‍♂️ Thank you!
